sudo: required
services:
  - docker

before_install:
  - docker build -t meltedspork/mutli-containers-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true meltedspork/mutli-containers-test npm test

after_success:
  - docker build -t meltedspork/mutli-containers-client ./client
  - docker build -t meltedspork/mutli-containers-nginx ./nginx
  - docker build -t meltedspork/mutli-containers-server ./server
  - docker build -t meltedspork/mutli-containers-worker ./worker
  - echo "$DOCKERPASSWORD" | docker login -u "$DOCKERID" --password-stdin
  - docker push meltedspork/mutli-containers-client
  - docker push meltedspork/mutli-containers-nginx
  - docker push meltedspork/mutli-containers-server
  - docker push meltedspork/mutli-containers-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-706479344561
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWSACCESSKEY
  secret_access_key:
    secure: $AWSSECRETKEY
